MODEL:
  META_ARCHITECTURE: "DecoupledGeneralizedRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NAME: "DecoupledRes5ROIHeads"
    NUM_CLASSES: 20
    BATCH_SIZE_PER_IMAGE: 256
  ANCHOR_GENERATOR:
    SIZES: [ [ 64, 128, 256, 512 ] ]
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
    BATCH_SIZE_PER_IMAGE: 128
  PROPOSAL_GENERATOR:
    NAME: "TLRPN"
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704,)
  MIN_SIZE_TEST: 608
  MAX_SIZE_TRAIN: 1166
DATASETS:
  TRAIN: ('voc_2007_trainval', 'voc_2012_trainval')
  TEST: ('voc_2007_test',)
SOLVER:
  STEPS: (3999, )
  MAX_ITER: 4000  # 16 epochs
  WARMUP_ITERS: 100
  CHECKPOINT_PERIOD: 1000
  IMS_PER_BATCH: 4
  BASE_LR: 0.00025
  LR_SCHEDULER_NAME: "ExponentialLR"
  GAMMA: 0.1
TEST:
  EVAL_PERIOD: 500
VIS_PERIOD: 20
VERSION: 2